name: Deploy via FTP para InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sincronizar arquivos
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Preparar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Instalar dependências PHP
        working-directory: AdotePatas
        run: |
          rm -rf vendor
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Sincronizar via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: AdotePatas/
          server-dir: htdocs/
